/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package key.SOURCEDB.HTH000PA.HTHPA;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class HTHPSE_T extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2189986427004281299L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HTHPSE_T\",\"namespace\":\"key.SOURCEDB.HTH000PA.HTHPA\",\"fields\":[{\"name\":\"IDMSGBAN_1\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"IDMSGBAN_2\",\"type\":\"string\",\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<HTHPSE_T> ENCODER =
      new BinaryMessageEncoder<HTHPSE_T>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<HTHPSE_T> DECODER =
      new BinaryMessageDecoder<HTHPSE_T>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<HTHPSE_T> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<HTHPSE_T> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<HTHPSE_T> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<HTHPSE_T>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this HTHPSE_T to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a HTHPSE_T from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a HTHPSE_T instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static HTHPSE_T fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence IDMSGBAN_1;
   private java.lang.CharSequence IDMSGBAN_2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HTHPSE_T() {}

  /**
   * All-args constructor.
   * @param IDMSGBAN_1 The new value for IDMSGBAN_1
   * @param IDMSGBAN_2 The new value for IDMSGBAN_2
   */
  public HTHPSE_T(java.lang.CharSequence IDMSGBAN_1, java.lang.CharSequence IDMSGBAN_2) {
    this.IDMSGBAN_1 = IDMSGBAN_1;
    this.IDMSGBAN_2 = IDMSGBAN_2;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return IDMSGBAN_1;
    case 1: return IDMSGBAN_2;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: IDMSGBAN_1 = (java.lang.CharSequence)value$; break;
    case 1: IDMSGBAN_2 = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'IDMSGBAN_1' field.
   * @return The value of the 'IDMSGBAN_1' field.
   */
  public java.lang.CharSequence getIDMSGBAN1() {
    return IDMSGBAN_1;
  }


  /**
   * Sets the value of the 'IDMSGBAN_1' field.
   * @param value the value to set.
   */
  public void setIDMSGBAN1(java.lang.CharSequence value) {
    this.IDMSGBAN_1 = value;
  }

  /**
   * Gets the value of the 'IDMSGBAN_2' field.
   * @return The value of the 'IDMSGBAN_2' field.
   */
  public java.lang.CharSequence getIDMSGBAN2() {
    return IDMSGBAN_2;
  }


  /**
   * Sets the value of the 'IDMSGBAN_2' field.
   * @param value the value to set.
   */
  public void setIDMSGBAN2(java.lang.CharSequence value) {
    this.IDMSGBAN_2 = value;
  }

  /**
   * Creates a new HTHPSE_T RecordBuilder.
   * @return A new HTHPSE_T RecordBuilder
   */
  public static key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder newBuilder() {
    return new key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder();
  }

  /**
   * Creates a new HTHPSE_T RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new HTHPSE_T RecordBuilder
   */
  public static key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder newBuilder(key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder other) {
    if (other == null) {
      return new key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder();
    } else {
      return new key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder(other);
    }
  }

  /**
   * Creates a new HTHPSE_T RecordBuilder by copying an existing HTHPSE_T instance.
   * @param other The existing instance to copy.
   * @return A new HTHPSE_T RecordBuilder
   */
  public static key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder newBuilder(key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T other) {
    if (other == null) {
      return new key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder();
    } else {
      return new key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder(other);
    }
  }

  /**
   * RecordBuilder for HTHPSE_T instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HTHPSE_T>
    implements org.apache.avro.data.RecordBuilder<HTHPSE_T> {

    private java.lang.CharSequence IDMSGBAN_1;
    private java.lang.CharSequence IDMSGBAN_2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.IDMSGBAN_1)) {
        this.IDMSGBAN_1 = data().deepCopy(fields()[0].schema(), other.IDMSGBAN_1);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.IDMSGBAN_2)) {
        this.IDMSGBAN_2 = data().deepCopy(fields()[1].schema(), other.IDMSGBAN_2);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing HTHPSE_T instance
     * @param other The existing instance to copy.
     */
    private Builder(key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.IDMSGBAN_1)) {
        this.IDMSGBAN_1 = data().deepCopy(fields()[0].schema(), other.IDMSGBAN_1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.IDMSGBAN_2)) {
        this.IDMSGBAN_2 = data().deepCopy(fields()[1].schema(), other.IDMSGBAN_2);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'IDMSGBAN_1' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDMSGBAN1() {
      return IDMSGBAN_1;
    }


    /**
      * Sets the value of the 'IDMSGBAN_1' field.
      * @param value The value of 'IDMSGBAN_1'.
      * @return This builder.
      */
    public key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder setIDMSGBAN1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.IDMSGBAN_1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'IDMSGBAN_1' field has been set.
      * @return True if the 'IDMSGBAN_1' field has been set, false otherwise.
      */
    public boolean hasIDMSGBAN1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'IDMSGBAN_1' field.
      * @return This builder.
      */
    public key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder clearIDMSGBAN1() {
      IDMSGBAN_1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'IDMSGBAN_2' field.
      * @return The value.
      */
    public java.lang.CharSequence getIDMSGBAN2() {
      return IDMSGBAN_2;
    }


    /**
      * Sets the value of the 'IDMSGBAN_2' field.
      * @param value The value of 'IDMSGBAN_2'.
      * @return This builder.
      */
    public key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder setIDMSGBAN2(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.IDMSGBAN_2 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'IDMSGBAN_2' field has been set.
      * @return True if the 'IDMSGBAN_2' field has been set, false otherwise.
      */
    public boolean hasIDMSGBAN2() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'IDMSGBAN_2' field.
      * @return This builder.
      */
    public key.SOURCEDB.HTH000PA.HTHPA.HTHPSE_T.Builder clearIDMSGBAN2() {
      IDMSGBAN_2 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public HTHPSE_T build() {
      try {
        HTHPSE_T record = new HTHPSE_T();
        record.IDMSGBAN_1 = fieldSetFlags()[0] ? this.IDMSGBAN_1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.IDMSGBAN_2 = fieldSetFlags()[1] ? this.IDMSGBAN_2 : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<HTHPSE_T>
    WRITER$ = (org.apache.avro.io.DatumWriter<HTHPSE_T>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<HTHPSE_T>
    READER$ = (org.apache.avro.io.DatumReader<HTHPSE_T>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.IDMSGBAN_1);

    out.writeString(this.IDMSGBAN_2);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.IDMSGBAN_1 = in.readString(this.IDMSGBAN_1 instanceof Utf8 ? (Utf8)this.IDMSGBAN_1 : null);

      this.IDMSGBAN_2 = in.readString(this.IDMSGBAN_2 instanceof Utf8 ? (Utf8)this.IDMSGBAN_2 : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.IDMSGBAN_1 = in.readString(this.IDMSGBAN_1 instanceof Utf8 ? (Utf8)this.IDMSGBAN_1 : null);
          break;

        case 1:
          this.IDMSGBAN_2 = in.readString(this.IDMSGBAN_2 instanceof Utf8 ? (Utf8)this.IDMSGBAN_2 : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










